[package]
name = "nano"
version = "0.2.0"
authors = ["DFINITY Team"]
edition = "2018"

[[bin]]
name = "nano"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.34"
candid = { version = "0.6.20", features = [ "random" ] }
chrono = "0.4.9"
clap = "3.0.0-beta.2"
crc32fast = "1.2.0"
hex = {version = "0.4.2", features = ["serde"] }
openssl = "0.10.32"
rust_decimal = "1.10.3"
serde = "1.0"
serde_cbor = "0.11.1"
serde_json = "1.0.57"
serde_bytes = "0.11.2"
tokio = { version = "1.2.0", features = [ "fs" ] }

[dependencies.ic-agent]
git = "https://github.com/dfinity/agent-rs.git"
rev = "95a0782cd6f432cb1e98ed9422cf9d7327236b17"
features = ["reqwest"]

[dependencies.ic-types]
git = "https://github.com/dfinity/agent-rs.git"
rev = "95a0782cd6f432cb1e98ed9422cf9d7327236b17"

[dependencies.ic-utils]
git = "https://github.com/dfinity/agent-rs.git"
rev = "95a0782cd6f432cb1e98ed9422cf9d7327236b17"

[patch.crates-io.ic-agent]
version = "0.3.0"
git = "https://github.com/dfinity/agent-rs.git"
rev = "95a0782cd6f432cb1e98ed9422cf9d7327236b17"

[patch.crates-io.ic-types]
version = "0.1.2"
git = "https://github.com/dfinity/agent-rs.git"
rev = "95a0782cd6f432cb1e98ed9422cf9d7327236b17"

[patch.crates-io.ic-utils]
version = "0.2.1"
git = "https://github.com/dfinity/agent-rs.git"
rev = "95a0782cd6f432cb1e98ed9422cf9d7327236b17"
