[workspace]

members = [
  "quill",
  # "ink",
]

[patch.crates-io.ic-agent]
git = "https://github.com/dfinity/agent-rs.git"
rev = "2e871f7cabc32a7b93a39197eaee6992a426d383"

[patch.crates-io.ic-types]
git = "https://github.com/dfinity/agent-rs.git"
rev = "2e871f7cabc32a7b93a39197eaee6992a426d383"
